---
- name: clone mango
  git:
    repo: "git@github.com/sugarcrm/mango.git"
    dest: ~/Documents/Sugar/Mango

- name: add silent install config
  copy:
    src: ../files/config_si.php
    dest: ~/Documents/Sugar/Mango/sugarcrm/config_si.php