---
- name: mk nvm dir
  file:
    path: ~/.nvm
    state: directory

- name: update .bash_profile
  blockinfile:
    path: ~/.bash_profile
    block: |
      export NVM_DIR=~/.nvm
      source $(brew --prefix nvm)/nvm.sh

- name: resource bash_profile and install node 8
  shell:
    cmd: source ~/.bash_profile; nvm install 8
